version: "3.4"
services:
  
  sonarqube:
    image: sonarqube:latest
    container_name: "SONARQUBE-DOCKER"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    restart: always
    expose:
      - 9000  
    ports:
      - "9000:9000"
    networks:
      - sonarnet

  sonarqube-db:
    image: postgres:latest
    container_name: "POSTGRES-SONARQUBE"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - "./sonar-data:/var/lib/postgresql/data/"
    restart: always  
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge



 
  
 
